### ISSUE TITLE
Does Not Work Wirth Python 2.7

### ISSUE THREAD

**Issue by derwassi** [mossblaser/plottie#1]
In ubuntu i had to Install pip dir python3 (pip3) and Had to Install plottie via pip3 command. 
Launching in Python 2.7 threw an Error about an unknown unicode encoding.
Maybe thendocumentation should ne updated accordingly

**Comment by mossblaser** [comment]
> Maybe thendocumentation should ne updated accordingly

Good point! Thank you!
