### ISSUE TITLE
Support for Automatic knives

### ISSUE THREAD

**Issue by derwassi** [mossblaser/plottie#3]
The Portrait 2 is shipped with an automatic knife. It gets adjusted at the start of a print automatically.
I can help with this, i just need some advice on how to tap into the USB protocol...

**Comment by mossblaser** [comment]
Ooh, that would be amazing! (As you'll guess I don't have this version, only the first generation!) Out of curiousity does plottie work usefully even without the automatic knife support?

Back when I was doing this I think the setup I used was a Windows VM to run Silhouette Studio (with USB passthrough) and then used wireshark to record what was passing over USB. If you were able to make a series of short recordings of the same simple shape being cut out, selecting a different knife setting each time, I could see if I could build a prototype for you to test out (and which could then be added to the plottie software).

**Comment by derwassi** [comment]
Thanks for getting into this!

The machine works without any problems with plottie, it uses the curretly selected knife-setting. The knife can also be set manually.

I captured the output with wireshark (a small diagonal cut). I made one file per knife setting. I also sniffed a plot with plottie (as reference):
[plots.zip](https://github.com/mossblaser/plottie/files/5111507/plots.zip)

I have no idea about the protocol, but by briefly looking through the captures, I found a FC18 TF[N] command (where N is the knife setting)

**Comment by mossblaser** [comment]
Fantastic work, thanks for your efforts -- I think it looks like you've done the hard work for me already! :)

Would you be able to test out the following simple test script to see if it does what it should?

```python
#!/usr/bin/env python3

import sys
from py_silhouette import SilhouetteDevice

knife_setting = int(sys.argv[1])

d = SilhouetteDevice()
d._send(b"TF%d,1\03"%(knife_setting))
d.flush()
```

Then run it with:

    $ python script.py <knife setting>

And run it with a few different settings (in a random order). It should simply change the knife setting and nothing more.

If that works, it looks like I'll be able to add this new command to [mossblaser/py_silhouette](https://github.com/mossblaser/py_silhouette) (the back-end for plottie) and then a suitable flag to the plottie CLI.

Thanks very much again!

**Comment by derwassi** [comment]
The script works as expected:-)

Thank you very much for all the effort!
