### ISSUE TITLE
Offset for cutting mat

### ISSUE THREAD

**Issue by derwassi** [mossblaser/plottie#7]
When i start a plot, which is close to the top of the page, the cut starts on the cutting mat, not on the checkered area where the cardstock is tacked to.
Is there a possibility to define the offset of the top part of the cutting mat?
As a workaround i enlarged my cutting area of the svg and added a helpline so i know, where the cuttable area is.
![image](https://user-images.githubusercontent.com/3707522/92157544-d652a900-ee2a-11ea-969c-e5479cee3128.png)

**Comment by mossblaser** [comment]
Ah, interesting.

My silhouette device has two buttons for inserting media (see picture below): one for when a cutting mat is used and one for when it isn't. When you press the cutting mat insert button it pulls the media in a bit further such that the grid part of the mat is roughly where it'll start cutting. Does the new Silhouette not such a button?

![Buttons](https://makingofamom.com/wp-content/uploads/2014/04/portrait-buttons-with-labels.jpg)

**Comment by derwassi** [comment]
No, it only has a load and unload Button. I assume the Software then does some resetting based on the machine type and selected Media. I can try to make some logs with wireshark again If you like.

**Comment by mossblaser** [comment]
Ah, I see!

Do you find that the registration mark finding process works well on your machine? If so, I could add a simple option to plottie which just adds a fixed y-offset and call it a day. (If this were the case, what would the offset be for your mat -- I could make that a default when no specific offset is given).

If you find the registration mark search seems to always end up looking in the wrong place it may be worth starting to sniff the protocol.

As always, thanks again for all your input and apologies for the slowness of my responses!
