### ISSUE TITLE
Using with the Portrait 3

### ISSUE THREAD

**Issue by gtebbutt** [mossblaser/plottie#9]
Firstly, big thanks for a great tool! Having something lightweight and scriptable saved me a ton of time and potential mistakes compared to having to do everything through a GUI. 

Good news is that it works well with the Portrait 3 hardware, just needed a few very minor adjustments to get things set up:
- Duplicating the Portrait 2 device definition in `py_silhouette`, renaming, and updating the USB ID to `0x113A` seems to send the correct settings, although I haven't tried anything too complicated with it so far.
- The cutting mat y-offset (https://github.com/mossblaser/plottie/issues/7) is a fixed value exactly twice the normal feed in, and regmarks work consistently after adjusting for that. Quick fix I used was to feed in once, power off, and then feed in again (https://github.com/fablabnbg/inkscape-silhouette/issues/128) - as long as the x-axis alignment you start with is good, that'll work pretty much every time. 
- I saw `No such device (it may have been disconnected)` errors from `pyusb` fairly frequently, but with no pattern I could immediately figure out. Could be something about my setup (Intel Mac, connected via some old USB A->C dongle I had in a drawer), and thankfully I got enough early successes to know for sure that it *did* work sometimes, so I just looped each command until it ran. I get the impression that fully figuring this out would be a ton of effort, but perhaps a short term fix to retry every 500ms or so for ~30 seconds would be worthwhile? 

This is my first time using any of Silhouette's plotters, so I'm pretty much figuring this out as I go, but if there's any device data it'd be useful to dump or anything like that just let me know.

**Comment by mossblaser** [comment]
Thanks very much for the kind words! I'm glad to hear you're finding plottie useful.

Regarding the USB ID, thanks for that, I'll try and get that added to pysilhouette.

Second, regarding the offset, am I right in thinking that a simple translation of everything down by the size of the mat margin would be sufficient? (I presume if you did this manually in your SVG things work as you expect?) If so, how large is that margin could you measure? As suggested in #7, I could try adding a CLI option to do this for you.

Finally, re the USB issues, that sounds very unusual: I've not encountered such a thing before. I'm afraid to say this is probably an artefact of the hardware you're using and I'd be reluctant to add any workarounds directly unless it was a wider issue. (Sorry!). On the plus side, it seems you're pretty good at sleuthing through the code so perhaps you'll be able to come up with a local patch which does what you need? (Feel free to share! If it does come up again it would be useful to have a solution ready to go!)

**Comment by mossblaser** [comment]
Just to let you know, I've released v0.5.0 of py_silhouette [which includes the new USB ID](https://github.com/mossblaser/py_silhouette/compare/v0.4.3...v0.5.0) Thanks very much for that!
